### ISSUE TITLE
ESModules are giving too much trouble

### ISSUE THREAD

**Issue by ilearnio** [sindresorhus/email-regex#12]
Just wanted to note here that I (and probably a lot of other people who installed this package) spent about 2 days trying to make this package work with our front-end and then back-end. A lot of changes had to be done to TypeScript, Node (package.json), Jest (had to mock it), Docker. A lot of wasted hours on googling and fixing different issues and eventually decided to stop it and switch to older version of this package (v4.0.0).

It would be great if it would support both ESM and CommonJS, using the new "exports" property that can be used to separate entry-points for CommonJS and ESM:

```js
// package.json
{
    "name": "my-package",
    "type": "module",
    "exports": {
        ".": {
            // Entry-point for `import "my-package"` in ESM
            "import": "./esm/index.js",
            // Entry-point for `require("my-package") in CJS
            "require": "./commonjs/index.cjs",
        },
    },
    // CJS fall-back for older versions of Node.js
    "main": "./commonjs/index.cjs",
}
```

**Comment by sindresorhus** [comment]
Node.js has supported ESM for a long time. The fact that TS and Jest lags behind in support is really their own fault. You are the one that chose to use TS and Jest. I cannot possibly be held responsible for any kind of tool people use. I support Node.js. That's it.

As for supporting note ESM and CommonJS, that comes with its own problems and does not work out in practice.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
