### ISSUE TITLE
`example.@gmail.com` should a invalid regexp

### ISSUE THREAD

**Issue by evagy** [sindresorhus/email-regex#5]
`example.@gmail.com` should a invalid email.
I think maybe this repo want check it, as below code in `index.js`
```JavaScript
const re = '[^\\.\\s@:][^\\s@:]*(?!\\.)@[^\\.\\s@]+(?:\\.[^\\.\\s@]+)*';
```
the regexp snippet `[^\\s@:]*(?!\\.)@` is also match `.@` 
Because the `?!` only match a position not a indeed character. It like `(?=@)@` equal to  `@`. and `(?![^@])@` equal to  `@`. the character before `@` always match the position `(?=@)` and `(?![^@])`, the regexp snippets in the repo code `(?!\\.)` is a subset of  `(?![^@])`, it is reason

* If, `emailRegex({exact: true}).test('example.@gmail.com')` return `true` is working as Intended. The regexp snippet `(?!\\.)` is useless, it should be remove. Just like below
```JavaScript
const re = '[^\\.\\s@:][^\\s@:]*@[^\\.\\s@]+(?:\\.[^\\.\\s@]+)*';
```

* If  `emailRegex({exact: true}).test('example.@gmail.com')` should return `false`, the regexp should change like below:
 ```JavaScript
const re = '[^\\.\\s@:](?:[^\\s@:]*[^\\s@:\\.])?@[^\\.\\s@]+(?:\\.[^\\.\\s@]+)*';
```

If it is the sencond position, I will pull request to fix it and add test.

**Comment by niftylettuce** [comment]
I have published <https://github.com/niftylettuce/email-regex-safe> as an alternative to this package, with a lot of configurable options.  PR's welcome.
